version: '3.4'

services:
  rvmini-dev:
    image: rvmini-dev
    build: .
    ports:
      - "2222:22"
    volumes:
      - ./riscv-mini:/root/riscv-mini
    environment:
      - SSH_DOCKER_PUB_KEY=${SSH_DOCKER_PUB_KEY}
      - GITHUB_PRIVATE_KEY=${GITHUB_PRIVATE_KEY}
    command: ["/bin/zsh", "-c", "echo $SSH_DOCKER_PUB_KEY > /root/.ssh/authorized_keys && chmod 600 /root/.ssh/authorized_keys && /etc/init.d/ssh restart && tail -f /dev/null"]

# echo $SSH_DOCKER_PUB_KEY > /root/.ssh/authorized_keys && 